# Generated by Django 3.0.6 on 2020-06-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='plot',
        ),
        migrations.AddField(
            model_name='show',
            name='genres',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userrating',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
