# Generated by Django 3.0.6 on 2020-06-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_auto_20200604_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
